config/routes.rb
Rails.application.routes.draw do
  get "contact-us", to: "pages#contact_us"
  get "services", to: "pages#services"
  get "about-us", to: "pages#about_us"
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "application"

  def home
  end

  def about_us
  end

  def services
  end

  def contact_us
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def breadcrumb(action)
    return action.humanize
  end

  def active(path)
    current_page?(path) ? "active" : ""
  end

end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    title Company
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body.slider-collapse
    #site-content
      header class="site-header wow fadeInDown"
        .container
          = render partial: "shared/header"
               
      main class="content"
        = yield

      footer class="site-footer wow fadeInUp"
        = render partial: "shared/footer"

app/views/pages/about_us.html.slim
.slider
  ul class="slides"
    li data-background="#{image_path('freight-logistics.jpg') }"
       .container
        .slide-caption-as-page-title
          h2 class="slide-title" OUR HISTORY
 
.fullwidth-block.less-padding
  .container
    .row
      .col-md-12
        .row
          .col-md-7.wow.fadeInLeft
            = image_tag "http://placehold.it/650x350"
              
          .col-md-5.wow.fadeInLeft
            p Amazing Spider-Man is the cornerstone of the Marvel Universe. Earths Mightiest Heroes reunite with their biggest guns at the forefront to take on familiar enemies and new threats alike. The Avengers return. Looking for the one superhero comic you just have to read.
            
            p Iron Man, Thor, Captain America and the rest of Earths Mightiest Heroes unite to stand against the threats none can face alone. See the Avengers go up against Ultron, Kang, the Masters of Evil and more over three decades of epic action. This is where youll find all the big-time action, major storylines and iconic Spider-Man magic youd come to expect from the Wall-Crawler. Meet all of Spideys deadly enemies, from the Green Goblin and Doctor Octopus to Venom and Carnage, plus see Peter Parker fall in love, face tragedy and triumph, and learn that with great power comes great responsibility.
      
.fullwidth-block.less-padding data-bg-color="#f1f1f1"
  .container
    h2 class="section-title" Our Team
    .row
      .col-md-6
        .team.wow.fadeInRight
          figure class="team-image"
            = image_tag "http://placehold.it/170x170"
            
          h2 class="team-name" Christian Brown
          small class="team-title" CEO
          p class="team-description" A gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. Avengers Assemble
          
        .team.wow.fadeInRight
          figure class="team-image"
            = image_tag "http://placehold.it/170x170"
          h2 class="team-name" Sarah Smith
          small class="team-title" PR Specialist
          p class="team-description" A gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. Avengers Assemble
          
      .col-md-6
        .team.wow.fadeInRight data-wow-delay=".4s"
          figure class="team-image"
            = image_tag "http://placehold.it/170x170"
          h2 class="team-name" Steven Blumkin
          small class="team-title" Director
          p class="team-description" A gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. Avengers Assemble
          
        .team.wow.fadeInRight data-wow-delay=".4s"
          figure class="team-image"
            = image_tag "http://placehold.it/170x170"
          h2 class="team-name" Jessica Webb
          small class="team-title" Consumer Service
          p class="team-description" A gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. Avengers Assemble

app/views/pages/contact_us.html.slim
.slider
  ul class="slides"
    li data-background="#{image_path('freight-logistics.jpg') }"
      .container
        .slide-caption-as-page-title
          h2 class="slide-title" OUR OFFICE

.fullwidth-block.less-padding
 .container
   .row
     .col-md-4.wow.fadeInLeft
       h4 COMPANY
       ul class="list-fa"
         li
           i.fa.fa-map-marker
           | Unit 4 Leovino Commercial BLDG. ML Quezon Brgy. San Roque, Antipolo City, Rizal, Philippines 1870
         li
           i.fa.fa-phone
           | +632-570-7482
         li
           i.fa.fa-mobile
           | Globe: 0916-692-1221
         li
           i.fa.fa-mobile
           | Smart: 0908-860-0950
         li
           i.fa.fa-envelope
           | company@test.com
           
       form action="#" class="contact-form"
         input type="text" placeholder="Your Name"
         input type="text" placeholder="Company Name"
         input type="text" placeholder="Email"
         textarea name="" id="" class="mceNoEditor" placeholder="Message"
         input type="submit" class="button" onclick="return false;" value="Send Message"
       
     .col-md-7.col-md-push-1.wow.fadeInRight
       .map
         iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3861.329184791343!2d121.17350931484!3d14.58030898981538!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397c0aa3bd6486d%3A0x66a7cb2bb285f738!2sLeovino+Commercial+Building%2C+16+M.L.+Quezon+Street%2C+Antipolo%2C+1870+Metro+Manila!5e0!3m2!1sen!2sph!4v1492675908024" width="600" height="520" frameborder="0" style="border:0" allowfullscreen

app/views/pages/home.html.slim
.slider
  ul class="slides"
    li data-background="#{image_path('freight-logistics.jpg') }"
      .container
        .slide-caption.col-md-4
          h2 class="slide-title" Welcome
          p Consectetur adipisicing elit. Dignissimos fuga eos nihil repellat et enim, neque, aliquid delectus quia hic praesentium sit, repudiandae pariatur deleniti vero.
          
.fullwidth-block data-bg-color="#f1f1f1"
  .container
    .jumbotron
      h1 style="text-align:center;" Content goes here

.fullwidth-block.offers-section
  .container
    .row
      .col-md-8.col-sm-8.col-xs-12
        h3 Content goes here
        article class="offer"
          h2 class="entry-title"
            a href="javascript:;" Nemo enim ipsam voluptatem
          p Piditate non provident similique sunt in culpa qui oficia deserunt molitia animi est aborum et dolorum fuga
          
      .col-md-4.col-sm-4.col-xs-12
        h3 Content goes here
        article class="offer"
          h2 class="entry-title"
            a href="javascript:;" Nemo enim ipsam voluptatem
          p Piditate non provident similique	sunt in culpa qui oficia deserunt molitia animi est aborum et dolorum fuga

app/views/pages/services.html.slim
.slider
  ul class="slides"
    li data-background="#{image_path('freight-logistics.jpg') }"
      .container
        .slide-caption-as-page-title
          h2 class="slide-title" SERVICES
 
.fullwidth-block.less-padding
  .container
    .filterable-items
      .filterable-item.south-america
        article class="offer-item"
          figure class="featured-image"
            img src="http://placehold.it/364x286" alt=""
          h2 class="entry-title"
            a href="javascript:;" Efficitur efficitur convallis
          p Sed vitae fermentum lacus in augue massa pellentesque mauris vel iaculis sclerisque nulla
      
      .filterable-item.south-america
        article class="offer-item"
          figure class="featured-image"
            img src="http://placehold.it/364x286" alt=""
          h2 class="entry-title"
            a href="javascript:;" Efficitur efficitur convallis
          p Sed vitae fermentum lacus in augue massa pellentesque mauris vel iaculis sclerisque nulla
      
      .filterable-item.south-america
        article class="offer-item"
          figure class="featured-image"
            img src="http://placehold.it/364x286" alt=""
          h2 class="entry-title"
            a href="javascript:;" Efficitur efficitur convallis
          p Sed vitae fermentum lacus in augue massa pellentesque mauris vel iaculis sclerisque nulla
      
      .filterable-item.south-america
        article class="offer-item"
          figure class="featured-image"
            img src="http://placehold.it/364x286" alt=""
          h2 class="entry-title"
            a href="javascript:;" Efficitur efficitur convallis
          p Sed vitae fermentum lacus in augue massa pellentesque mauris vel iaculis sclerisque nulla
      
      .filterable-item.south-america
        article class="offer-item"
          figure class="featured-image"
            img src="http://placehold.it/364x286" alt=""
          h2 class="entry-title"
            a href="javascript:;" Efficitur efficitur convallis
          p Sed vitae fermentum lacus in augue massa pellentesque mauris vel iaculis sclerisque nulla
      
      .filterable-item.south-america
        article class="offer-item"
          figure class="featured-image"
            img src="http://placehold.it/364x286" alt=""
          h2 class="entry-title"
            a href="javascript:;" Efficitur efficitur convallis
          p Sed vitae fermentum lacus in augue massa pellentesque mauris vel iaculis sclerisque nulla

app/views/shared/_footer.html.slim
.colophon
  .container
    p.copy
      | Copyright 2017 Company, Designed by
      | &nbsp;
      a href="http://www.themezy.com" target="_blank" Themezy
      | , All right reserved.

app/views/shared/_header.html.slim
div class="header-content transparent"
  .branding
    = image_tag "logo.png", class: "logo", alt: "Company Name"
    h1 class="site-title"
      a href="#{root_path}" Company
    small class="site-description" Tagline goes here

  nav.main-navigation
    button type="button" class="menu-toggle"
      i.fa.fa-bars
    ul.menu
      li class="menu-item #{active(about_us_path)}"
        a href="#{about_us_path}" About us
      li class="menu-item #{active(services_path)}"
        a href="#{services_path}" Services
      li class="menu-item #{active(contact_us_path)}"
        a href="#{contact_us_path}" Contact us

  .social-links
    a href="javascript:;" class="facebook" target="_blank"
      i.fa.fa-facebook
    a href="javascript:;" class="twitter" target="_blank"
      i.fa.fa-twitter
    a href="javascript:;" class="youtube" target="_blank"
      i.fa.fa-youtube
    a href="javascript:;" class="skype" target="_blank"
      i.fa.fa-skype